config/routes.rb
Rails.application.routes.draw do

  get 'restore/create'
  post 'restore/load'

  devise_for :users
  resources :animals
  resources :clients
  root to: 'clients#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
	belongs_to :client
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
	has_many :animals, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]

  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.all.order(:name)
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
    @selected = params[:format]
  end

  # GET /animals/1/edit
  def edit
    @selected = @animal.client_id
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)
    @selected = @animal.client_id
    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    @selected = @animal.client_id
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: 'Animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:client_id, :name, :starting_date, :categorie, :vaccin ,:API1 ,:API2 ,:API3 ,:API4 ,:APE1 ,:APE2 ,:APE3 ,:consult)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all.order(:name)
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name)
    end
end

app/controllers/restore_controller.rb
class RestoreController < ApplicationController

  def create
  	system 'rake db:seed:dump MODELS="Client, Animal" FILE=db/backup.rb EXCLUDE=Null'
  	send_file "#{Rails.root}/db/backup.rb"
  end

  def load
	# upload file
	File.open("#{Rails.root}/db/seeds.rb", 'wb') do |file|
		file.write(params[:file].read)
	end
	# clean existing data
	Client.destroy_all
	Animal.destroy_all
	# seed database from file uploaded
	system 'rake db:seed'
  	redirect_to root_path
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/restore_helper.rb
module RestoreHelper
end

app/views/animals/_form.html.erb
<%= form_with(model: animal, local: true) do |form| %>
  <% if animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= label_tag :client %>
  <%= form.select(:client_id, options_for_select((Client.all.order(:name).map { |c| [c.name, c.id] }).unshift(["Select client", nil]), selected: @selected)) %>
  <br/>
  <%= label_tag :name %>
  <%= text_field :animal, :name %>
  <br>
  <%= label_tag :categorie %>
  <%= text_field :animal, :categorie %>
  <br>
<ul>

<li>Starting date : <%= text_field :animal, :starting_date, class: "datepicker" %></li>
<li>Vaccin : <%= text_field :animal, :vaccin, class: "datepicker" %></li>
<li>API1 : <%= text_field :animal, :API1, class: "datepicker" %></li>
<li>API2 : <%= text_field :animal, :API2, class: "datepicker" %></li>
<li>API3 : <%= text_field :animal, :API3, class: "datepicker" %></li>
<li>API4 : <%= text_field :animal, :API4, class: "datepicker" %></li>
<li>APE1 : <%= text_field :animal, :APE1, class: "datepicker" %></li>
<li>APE2 : <%= text_field :animal, :APE2, class: "datepicker" %></li>
<li>APE3 : <%= text_field :animal, :APE3, class: "datepicker" %></li>
<li>Consult : <%= text_field :animal, :consult, class: "datepicker" %></li>
</ul>

  <br/>
  <div class="actions">
    <%= form.submit class: "btn" %>
  </div>
<% end %>
<br/>

<script type="text/javascript">
document.addEventListener('DOMContentLoaded', function() {
  var elems = document.querySelectorAll('.datepicker');
  var instances = M.Datepicker.init(elems, {
    showClearBtn: true
  });
});
  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('select');
    var instances = M.FormSelect.init(elems, null);
  });
</script>

app/views/animals/edit.html.erb
<h1>Editing Animal - <%= @animal.name %></h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Show', @animal %> |
<%= link_to 'Back', animals_path %>

app/views/animals/index.html.erb
<h1>Animals</h1>

<%= link_to 'New Animal', new_animal_path %>

<table>
  <thead>
    <tr>
      <th>animal</th>
      <th>client</th>
      <th>categorie</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @animals.each do |animal| %>
      <tr>
        <td><%= link_to animal.name, animal_path(animal) %></td>
        <td><%= link_to animal.client.name, client_path(animal.client) %></td>
        <td><%= animal.categorie %></td>
        <td><%= link_to 'Edit', edit_animal_path(animal) %></td>
        <td><%= link_to 'Destroy', animal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/animals/new.html.erb
<h1>New Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Back', animals_path %>

app/views/animals/show.html.erb
<h1><%= @animal.name %></h1>
<h2>client : <%= link_to @animal.client.name, client_path(@animal.client) %></h2>
<h2>categorie : <%= @animal.categorie %></h2>
<ul>
	<li>starting date : <%= @animal.starting_date.strftime("%d/%m/%Y") if !@animal.starting_date.nil? %></li>
	<li>vaccin : <%= @animal.vaccin.strftime("%d/%m/%Y") if !@animal.vaccin.nil? %></li>
	<li>API1 : <%= @animal.API1.strftime("%d/%m/%Y") if !@animal.API1.nil? %></li>
	<li>API2 : <%= @animal.API2.strftime("%d/%m/%Y") if !@animal.API2.nil? %></li>
	<li>API3 : <%= @animal.API3.strftime("%d/%m/%Y") if !@animal.API3.nil? %></li>
	<li>API4 : <%= @animal.API4.strftime("%d/%m/%Y") if !@animal.API4.nil? %></li>
	<li>APE1 : <%= @animal.APE1.strftime("%d/%m/%Y") if !@animal.APE1.nil? %></li>
	<li>APE2 : <%= @animal.APE2.strftime("%d/%m/%Y") if !@animal.APE2.nil? %></li>
	<li>APE3 : <%= @animal.APE3.strftime("%d/%m/%Y") if !@animal.APE3.nil? %></li>
	<li>consult : <%= @animal.consult.strftime("%d/%m/%Y") if !@animal.consult.nil? %></li>
</ul>

Created at :<%= @animal.created_at.strftime("%d/%m/%Y") %><br/>
Updated at :<%= @animal.updated_at.strftime("%d/%m/%Y") %><br/>

<br/>
<%= link_to 'Edit', edit_animal_path(@animal) %> |
<%= link_to 'Back', animals_path %>

<br/>
<br/>
<%= link_to 'Destroy', @animal, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= label_tag :name %>
  <%= text_field :client, :name %>

  <div class="actions">
    <%= form.submit class: "btn" %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Clients</h1>

<%= link_to 'New Client', new_client_path %> | 
<%= link_to "Show animals", animals_path %> |

<table>
  <thead>
    <tr>
      <th>client</th>
      <th>animals</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= link_to client.name, client_path(client) %></td>
        <td><% client.animals.each do |a| %><%= link_to a.name, animal_path(a) %>,<% end %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>
<br>
<br>
<br>
<div class="divider"></div>
<h1>Backup</h1>

<h5>Create backup</h5>
<%= link_to "Get backup", restore_create_path, class: "btn green" %>

<h5>Load backup</h5>
<%= form_tag restore_load_url, :multipart => true  do |f| %>
  <%= file_field_tag :file %><br/>
  <%= submit_tag "load backup", class: "btn red" %>
<% end %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<h1><%= @client.name %></h1>
<div class="card">
<div class="card-content">
	<span class="card-title">Animals</span>
	<ul>
	<% @client.animals.each do |a| %>
	<li><%= link_to a.name, animal_path(a) %></li>
	<% end %>
	</ul>
	<div class="card-action">
		<%= link_to "New animal", new_animal_path(@client) %>
	</div>
</div>
</div>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Veto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>

  <body>

<nav>
  <div class="nav-wrapper">
    <%= link_to "Vetoplan 👹", root_path, class: "brand-logo" %>
    <ul id="nav-mobile" class="right">
      <li><%= link_to "clients", clients_path %></li>
      <li><%= link_to "animals", animals_path %></li>
      <li><%= link_to('Logout', destroy_user_session_path, method: :delete, style: "float: rigth;") %></li>
    </ul>
  </div>
</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="container">
  <%= yield %>
</div>
  </body>
</html>

app/views/restore/create.html.erb
<h1>Restore#create</h1>
<p>Find me in app/views/restore/create.html.erb</p>

app/views/restore/load.html.erb
<h1>Restore#load</h1>
<p>Find me in app/views/restore/load.html.erb</p>